tools:
    php_cs_fixer: true
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            excluded_paths:       [ "Tests/GearmanClientStub.php" ]
    php_mess_detector:
        filter:
            excluded_paths:       [ "Tests/GearmanClientStub.php" ]
    php_analyzer:
        filter:
            excluded_paths: [ "*/Tests/*" ]
    sensiolabs_security_checker: true
